unit ExcelReportTests;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, ReportsBase, Classes, Barcode, Contnrs, SysUtils, XIntf, CommonIntf,
  Graphics, ExcelXP;

type

   TStubExcelReport = class (TExcelReportBase)
   protected
     procedure Execute;override;
   end;
  // Test methods for class TReportBase


  TestTExcelReportBase = class(TTestCase)
  strict private
    FExcelReportBase: TExcelReportBase;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestInsertGraphics;
  end;

implementation
uses
 Vcl.Imaging.pngimage;


procedure TestTExcelReportBase.SetUp;
begin
  FExcelReportBase := TStubExcelReport.Create(nil);
end;

procedure TestTExcelReportBase.TearDown;
begin
  //FExcelReportBase.Quit;
  //FExcelReportBase.Free;
  FExcelReportBase := nil;
end;

procedure TestTExcelReportBase.TestInsertGraphics;
begin

  FExcelReportBase.BuildReport;
  FExcelReportBase.Show;
end;

{ TStubExcelReport }

procedure TStubExcelReport.Execute;
var
  Graphics: TGraphic;
begin
  inherited;
  Graphics := TPngImage.Create;
  Graphics.LoadFromFile('VK.PNG');
  InsertGraphics(Graphics, '.png', 2, 5, 150, 150);
end;

initialization
  // Register any test cases with the test runner
 // RegisterTest(TestTReportBase.Suite);
  RegisterTest(TestTExcelReportBase.Suite);
end.

