object ImageFullSizeShowForm: TImageFullSizeShowForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'ImageFullSizeShowForm'
  ClientHeight = 181
  ClientWidth = 207
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -10
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnClick = FormClick
  OnMouseLeave = FormMouseLeave
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 12
end
