//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelphiAnalyser.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>.pas</string>\r\n  <string>.dpr</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Extensions
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["Extensions"]));
            }
            set
            {
                this["Extensions"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public string OpenWithExecutable
        {
            get
            {
                return ((string)(this["OpenWithExecutable"]));
            }
            set
            {
                this["OpenWithExecutable"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public string OpenWithCmd
        {
            get
            {
                return ((string)(this["OpenWithCmd"]));
            }
            set
            {
                this["OpenWithCmd"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings DigitsInId
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings)(this["DigitsInId"]));
            }
            set
            {
                this["DigitsInId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.IdLengthSettings IdLength
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.IdLengthSettings)(this["IdLength"]));
            }
            set
            {
                this["IdLength"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.FuncParamCountSettings FuncParamCount
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.FuncParamCountSettings)(this["FuncParamCount"]));
            }
            set
            {
                this["FuncParamCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings ConstantExpression
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings)(this["ConstantExpression"]));
            }
            set
            {
                this["ConstantExpression"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.CaseConditionSettings CaseCondition
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.CaseConditionSettings)(this["CaseCondition"]));
            }
            set
            {
                this["CaseCondition"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings PublicMember
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings)(this["PublicMember"]));
            }
            set
            {
                this["PublicMember"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings NoSectionDirective
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings)(this["NoSectionDirective"]));
            }
            set
            {
                this["NoSectionDirective"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.RegularSettings Regulars
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.RegularSettings)(this["Regulars"]));
            }
            set
            {
                this["Regulars"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.DfmIdsSettings DfmInclusion
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.DfmIdsSettings)(this["DfmInclusion"]));
            }
            set
            {
                this["DfmInclusion"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SettingsSerializeAs(System.Configuration.SettingsSerializeAs.Binary)]
        public global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings EmptyBody
        {
            get
            {
                return ((global::DelphiAnalyser.Analysers.StaticAnalysers.AnalyserSettings.BaseStaticSettings)(this["EmptyBody"]));
            }
            set
            {
                this["EmptyBody"] = value;
            }
        }
    }
}
