//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbitImportService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IImportService")]
    public interface IImportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDictionariesList", ReplyAction="http://tempuri.org/IImportService/GetDictionariesListResponse")]
        System.Xml.Linq.XElement GetDictionariesList(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDictionariesList", ReplyAction="http://tempuri.org/IImportService/GetDictionariesListResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDictionariesListAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDictionaryDetails", ReplyAction="http://tempuri.org/IImportService/GetDictionaryDetailsResponse")]
        System.Xml.Linq.XElement GetDictionaryDetails(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDictionaryDetails", ReplyAction="http://tempuri.org/IImportService/GetDictionaryDetailsResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDictionaryDetailsAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetInstitutionInfo", ReplyAction="http://tempuri.org/IImportService/GetInstitutionInfoResponse")]
        System.Xml.Linq.XElement GetInstitutionInfo(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetInstitutionInfo", ReplyAction="http://tempuri.org/IImportService/GetInstitutionInfoResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetInstitutionInfoAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetInstitutionPartOfInfo", ReplyAction="http://tempuri.org/IImportService/GetInstitutionPartOfInfoResponse")]
        System.Xml.Linq.XElement GetInstitutionPartOfInfo(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetInstitutionPartOfInfo", ReplyAction="http://tempuri.org/IImportService/GetInstitutionPartOfInfoResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetInstitutionPartOfInfoAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoImport", ReplyAction="http://tempuri.org/IImportService/DoImportResponse")]
        System.Xml.Linq.XElement DoImport(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoImport", ReplyAction="http://tempuri.org/IImportService/DoImportResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoImportAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoImportApplicationSingle", ReplyAction="http://tempuri.org/IImportService/DoImportApplicationSingleResponse")]
        System.Xml.Linq.XElement DoImportApplicationSingle(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoImportApplicationSingle", ReplyAction="http://tempuri.org/IImportService/DoImportApplicationSingleResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoImportApplicationSingleAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetImportResult", ReplyAction="http://tempuri.org/IImportService/GetImportResultResponse")]
        System.Xml.Linq.XElement GetImportResult(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetImportResult", ReplyAction="http://tempuri.org/IImportService/GetImportResultResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetImportResultAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoValidate", ReplyAction="http://tempuri.org/IImportService/DoValidateResponse")]
        System.Xml.Linq.XElement DoValidate(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoValidate", ReplyAction="http://tempuri.org/IImportService/DoValidateResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoValidateAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoDelete", ReplyAction="http://tempuri.org/IImportService/DoDeleteResponse")]
        System.Xml.Linq.XElement DoDelete(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoDelete", ReplyAction="http://tempuri.org/IImportService/DoDeleteResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoDeleteAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDeleteResult", ReplyAction="http://tempuri.org/IImportService/GetDeleteResultResponse")]
        System.Xml.Linq.XElement GetDeleteResult(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetDeleteResult", ReplyAction="http://tempuri.org/IImportService/GetDeleteResultResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDeleteResultAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoCheckApplication", ReplyAction="http://tempuri.org/IImportService/DoCheckApplicationResponse")]
        System.Xml.Linq.XElement DoCheckApplication(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoCheckApplication", ReplyAction="http://tempuri.org/IImportService/DoCheckApplicationResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoCheckApplicationAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoCheckApplicationSingle", ReplyAction="http://tempuri.org/IImportService/DoCheckApplicationSingleResponse")]
        System.Xml.Linq.XElement DoCheckApplicationSingle(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/DoCheckApplicationSingle", ReplyAction="http://tempuri.org/IImportService/DoCheckApplicationSingleResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoCheckApplicationSingleAsync(System.Xml.Linq.XElement data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestImport", ReplyAction="http://tempuri.org/IImportService/GetTestImportResponse")]
        System.Xml.Linq.XElement GetTestImport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestImport", ReplyAction="http://tempuri.org/IImportService/GetTestImportResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestImportAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestRemove", ReplyAction="http://tempuri.org/IImportService/GetTestRemoveResponse")]
        System.Xml.Linq.XElement GetTestRemove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestRemove", ReplyAction="http://tempuri.org/IImportService/GetTestRemoveResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestRemoveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestDictionariesList", ReplyAction="http://tempuri.org/IImportService/GetTestDictionariesListResponse")]
        System.Xml.Linq.XElement GetTestDictionariesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestDictionariesList", ReplyAction="http://tempuri.org/IImportService/GetTestDictionariesListResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestDictionariesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestDictionaryDetails", ReplyAction="http://tempuri.org/IImportService/GetTestDictionaryDetailsResponse")]
        System.Xml.Linq.XElement GetTestDictionaryDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestDictionaryDetails", ReplyAction="http://tempuri.org/IImportService/GetTestDictionaryDetailsResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestDictionaryDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestCheckApplication", ReplyAction="http://tempuri.org/IImportService/GetTestCheckApplicationResponse")]
        System.Xml.Linq.XElement GetTestCheckApplication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImportService/GetTestCheckApplication", ReplyAction="http://tempuri.org/IImportService/GetTestCheckApplicationResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestCheckApplicationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImportServiceChannel : AbitImportService.ServiceReference.IImportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportServiceClient : System.ServiceModel.ClientBase<AbitImportService.ServiceReference.IImportService>, AbitImportService.ServiceReference.IImportService {
        
        public ImportServiceClient() {
        }
        
        public ImportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement GetDictionariesList(System.Xml.Linq.XElement data) {
            return base.Channel.GetDictionariesList(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDictionariesListAsync(System.Xml.Linq.XElement data) {
            return base.Channel.GetDictionariesListAsync(data);
        }
        
        public System.Xml.Linq.XElement GetDictionaryDetails(System.Xml.Linq.XElement data) {
            return base.Channel.GetDictionaryDetails(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDictionaryDetailsAsync(System.Xml.Linq.XElement data) {
            return base.Channel.GetDictionaryDetailsAsync(data);
        }
        
        public System.Xml.Linq.XElement GetInstitutionInfo(System.Xml.Linq.XElement data) {
            return base.Channel.GetInstitutionInfo(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetInstitutionInfoAsync(System.Xml.Linq.XElement data) {
            return base.Channel.GetInstitutionInfoAsync(data);
        }
        
        public System.Xml.Linq.XElement GetInstitutionPartOfInfo(System.Xml.Linq.XElement data) {
            return base.Channel.GetInstitutionPartOfInfo(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetInstitutionPartOfInfoAsync(System.Xml.Linq.XElement data) {
            return base.Channel.GetInstitutionPartOfInfoAsync(data);
        }
        
        public System.Xml.Linq.XElement DoImport(System.Xml.Linq.XElement data) {
            return base.Channel.DoImport(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoImportAsync(System.Xml.Linq.XElement data) {
            return base.Channel.DoImportAsync(data);
        }
        
        public System.Xml.Linq.XElement DoImportApplicationSingle(System.Xml.Linq.XElement data) {
            return base.Channel.DoImportApplicationSingle(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoImportApplicationSingleAsync(System.Xml.Linq.XElement data) {
            return base.Channel.DoImportApplicationSingleAsync(data);
        }
        
        public System.Xml.Linq.XElement GetImportResult(System.Xml.Linq.XElement data) {
            return base.Channel.GetImportResult(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetImportResultAsync(System.Xml.Linq.XElement data) {
            return base.Channel.GetImportResultAsync(data);
        }
        
        public System.Xml.Linq.XElement DoValidate(System.Xml.Linq.XElement data) {
            return base.Channel.DoValidate(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoValidateAsync(System.Xml.Linq.XElement data) {
            return base.Channel.DoValidateAsync(data);
        }
        
        public System.Xml.Linq.XElement DoDelete(System.Xml.Linq.XElement data) {
            return base.Channel.DoDelete(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoDeleteAsync(System.Xml.Linq.XElement data) {
            return base.Channel.DoDeleteAsync(data);
        }
        
        public System.Xml.Linq.XElement GetDeleteResult(System.Xml.Linq.XElement data) {
            return base.Channel.GetDeleteResult(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetDeleteResultAsync(System.Xml.Linq.XElement data) {
            return base.Channel.GetDeleteResultAsync(data);
        }
        
        public System.Xml.Linq.XElement DoCheckApplication(System.Xml.Linq.XElement data) {
            return base.Channel.DoCheckApplication(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoCheckApplicationAsync(System.Xml.Linq.XElement data) {
            return base.Channel.DoCheckApplicationAsync(data);
        }
        
        public System.Xml.Linq.XElement DoCheckApplicationSingle(System.Xml.Linq.XElement data) {
            return base.Channel.DoCheckApplicationSingle(data);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> DoCheckApplicationSingleAsync(System.Xml.Linq.XElement data) {
            return base.Channel.DoCheckApplicationSingleAsync(data);
        }
        
        public System.Xml.Linq.XElement GetTestImport() {
            return base.Channel.GetTestImport();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestImportAsync() {
            return base.Channel.GetTestImportAsync();
        }
        
        public System.Xml.Linq.XElement GetTestRemove() {
            return base.Channel.GetTestRemove();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestRemoveAsync() {
            return base.Channel.GetTestRemoveAsync();
        }
        
        public System.Xml.Linq.XElement GetTestDictionariesList() {
            return base.Channel.GetTestDictionariesList();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestDictionariesListAsync() {
            return base.Channel.GetTestDictionariesListAsync();
        }
        
        public System.Xml.Linq.XElement GetTestDictionaryDetails() {
            return base.Channel.GetTestDictionaryDetails();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestDictionaryDetailsAsync() {
            return base.Channel.GetTestDictionaryDetailsAsync();
        }
        
        public System.Xml.Linq.XElement GetTestCheckApplication() {
            return base.Channel.GetTestCheckApplication();
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> GetTestCheckApplicationAsync() {
            return base.Channel.GetTestCheckApplicationAsync();
        }
    }
}
