#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbitServices.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UGTU")]
	public partial class AbitDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertABIT_Report(ABIT_Report instance);
    partial void UpdateABIT_Report(ABIT_Report instance);
    partial void DeleteABIT_Report(ABIT_Report instance);
    #endregion
		
		public AbitDataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["UGTUConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AbitDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbitDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbitDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AbitDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ABIT_Report> ABIT_Reports
		{
			get
			{
				return this.GetTable<ABIT_Report>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Abit_StatisticNew", IsComposable=true)]
		public IQueryable<Abit_StatisticNewResult> Abit_StatisticNew([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nnyear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idreport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> day_beg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kol)
		{
			return this.CreateMethodCallQuery<Abit_StatisticNewResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nnyear, idreport, day_beg, kol);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Abit_StatisticPodlin", IsComposable=true)]
		public IQueryable<Abit_StatisticPodlinResult> Abit_StatisticPodlin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nnyear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idreport, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> day_beg, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> kol)
		{
			return this.CreateMethodCallQuery<Abit_StatisticPodlinResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nnyear, idreport, day_beg, kol);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Abit_StatisticPlan", IsComposable=true)]
		public IQueryable<Abit_StatisticPlanResult> Abit_StatisticPlan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nnyear, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idreport)
		{
			return this.CreateMethodCallQuery<Abit_StatisticPlanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nnyear, idreport);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ABIT_Report")]
	public partial class ABIT_Report : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDReport;
		
		private string _ReportName;
		
		private System.Nullable<int> _RecordOrder;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDReportChanging(int value);
    partial void OnIDReportChanged();
    partial void OnReportNameChanging(string value);
    partial void OnReportNameChanged();
    partial void OnRecordOrderChanging(System.Nullable<int> value);
    partial void OnRecordOrderChanged();
    #endregion
		
		public ABIT_Report()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDReport", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDReport
		{
			get
			{
				return this._IDReport;
			}
			set
			{
				if ((this._IDReport != value))
				{
					this.OnIDReportChanging(value);
					this.SendPropertyChanging();
					this._IDReport = value;
					this.SendPropertyChanged("IDReport");
					this.OnIDReportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ReportName
		{
			get
			{
				return this._ReportName;
			}
			set
			{
				if ((this._ReportName != value))
				{
					this.OnReportNameChanging(value);
					this.SendPropertyChanging();
					this._ReportName = value;
					this.SendPropertyChanged("ReportName");
					this.OnReportNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordOrder", DbType="Int")]
		public System.Nullable<int> RecordOrder
		{
			get
			{
				return this._RecordOrder;
			}
			set
			{
				if ((this._RecordOrder != value))
				{
					this.OnRecordOrderChanging(value);
					this.SendPropertyChanging();
					this._RecordOrder = value;
					this.SendPropertyChanged("RecordOrder");
					this.OnRecordOrderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Abit_StatisticNewResult
	{
		
		private System.Nullable<int> _nnrecord;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _cShort_spec;
		
		private string _CShort_name_fac;
		
		private System.Nullable<int> @__1;
		
		private System.Nullable<int> @__2;
		
		private System.Nullable<int> @__3;
		
		public Abit_StatisticNewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nnrecord", DbType="Int")]
		public System.Nullable<int> nnrecord
		{
			get
			{
				return this._nnrecord;
			}
			set
			{
				if ((this._nnrecord != value))
				{
					this._nnrecord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cShort_spec", DbType="VarChar(100)")]
		public string cShort_spec
		{
			get
			{
				return this._cShort_spec;
			}
			set
			{
				if ((this._cShort_spec != value))
				{
					this._cShort_spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CShort_name_fac", DbType="VarChar(100)")]
		public string CShort_name_fac
		{
			get
			{
				return this._CShort_name_fac;
			}
			set
			{
				if ((this._CShort_name_fac != value))
				{
					this._CShort_name_fac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Int")]
		public System.Nullable<int> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.@__1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Int")]
		public System.Nullable<int> _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.@__2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3]", Storage="__3", DbType="Int")]
		public System.Nullable<int> _3
		{
			get
			{
				return this.@__3;
			}
			set
			{
				if ((this.@__3 != value))
				{
					this.@__3 = value;
				}
			}
		}
	}
	
	public partial class Abit_StatisticPodlinResult
	{
		
		private System.Nullable<int> _nnrecord;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _cShort_spec;
		
		private string _CShort_name_fac;
		
		private System.Nullable<int> @__1;
		
		private System.Nullable<int> @__2;
		
		private System.Nullable<int> @__3;
		
		public Abit_StatisticPodlinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nnrecord", DbType="Int")]
		public System.Nullable<int> nnrecord
		{
			get
			{
				return this._nnrecord;
			}
			set
			{
				if ((this._nnrecord != value))
				{
					this._nnrecord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this._date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cShort_spec", DbType="VarChar(100)")]
		public string cShort_spec
		{
			get
			{
				return this._cShort_spec;
			}
			set
			{
				if ((this._cShort_spec != value))
				{
					this._cShort_spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CShort_name_fac", DbType="VarChar(100)")]
		public string CShort_name_fac
		{
			get
			{
				return this._CShort_name_fac;
			}
			set
			{
				if ((this._CShort_name_fac != value))
				{
					this._CShort_name_fac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Int")]
		public System.Nullable<int> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.@__1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Int")]
		public System.Nullable<int> _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.@__2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3]", Storage="__3", DbType="Int")]
		public System.Nullable<int> _3
		{
			get
			{
				return this.@__3;
			}
			set
			{
				if ((this.@__3 != value))
				{
					this.@__3 = value;
				}
			}
		}
	}
	
	public partial class Abit_StatisticPlanResult
	{
		
		private System.Nullable<int> _nnrecord;
		
		private string _cShort_spec;
		
		private string _CShort_name_fac;
		
		private string _Sh_spec;
		
		private System.Nullable<int> @__1;
		
		private System.Nullable<int> @__2;
		
		private System.Nullable<int> @__3;
		
		public Abit_StatisticPlanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nnrecord", DbType="Int")]
		public System.Nullable<int> nnrecord
		{
			get
			{
				return this._nnrecord;
			}
			set
			{
				if ((this._nnrecord != value))
				{
					this._nnrecord = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cShort_spec", DbType="VarChar(100)")]
		public string cShort_spec
		{
			get
			{
				return this._cShort_spec;
			}
			set
			{
				if ((this._cShort_spec != value))
				{
					this._cShort_spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CShort_name_fac", DbType="VarChar(100)")]
		public string CShort_name_fac
		{
			get
			{
				return this._CShort_name_fac;
			}
			set
			{
				if ((this._CShort_name_fac != value))
				{
					this._CShort_name_fac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sh_spec", DbType="VarChar(10)")]
		public string Sh_spec
		{
			get
			{
				return this._Sh_spec;
			}
			set
			{
				if ((this._Sh_spec != value))
				{
					this._Sh_spec = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1]", Storage="__1", DbType="Int")]
		public System.Nullable<int> _1
		{
			get
			{
				return this.@__1;
			}
			set
			{
				if ((this.@__1 != value))
				{
					this.@__1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2]", Storage="__2", DbType="Int")]
		public System.Nullable<int> _2
		{
			get
			{
				return this.@__2;
			}
			set
			{
				if ((this.@__2 != value))
				{
					this.@__2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[3]", Storage="__3", DbType="Int")]
		public System.Nullable<int> _3
		{
			get
			{
				return this.@__3;
			}
			set
			{
				if ((this.@__3 != value))
				{
					this.@__3 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
