//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleTest.ScheduleServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class FacInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class SpecInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class DepInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class GroupInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class TeacherInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private int TabNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DutyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TabNum {
            get {
                return this.TabNumField;
            }
            set {
                if ((this.TabNumField.Equals(value) != true)) {
                    this.TabNumField = value;
                    this.RaisePropertyChanged("TabNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Duty {
            get {
                return this.DutyField;
            }
            set {
                if ((object.ReferenceEquals(this.DutyField, value) != true)) {
                    this.DutyField = value;
                    this.RaisePropertyChanged("Duty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LessonInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class LessonInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BeginsField;
        
        private System.DateTime EndsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Begins {
            get {
                return this.BeginsField;
            }
            set {
                if ((this.BeginsField.Equals(value) != true)) {
                    this.BeginsField = value;
                    this.RaisePropertyChanged("Begins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Ends {
            get {
                return this.EndsField;
            }
            set {
                if ((this.EndsField.Equals(value) != true)) {
                    this.EndsField = value;
                    this.RaisePropertyChanged("Ends");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class EventInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleTest.ScheduleServiceReference.RepeatPatternInfo PatternField;
        
        private int IDField;
        
        private System.DateTime BeginField;
        
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisciplineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherField;
        
        private bool IsMovedField;
        
        private int PatternIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ConsoleTest.ScheduleServiceReference.RepeatPatternInfo Pattern {
            get {
                return this.PatternField;
            }
            set {
                if ((object.ReferenceEquals(this.PatternField, value) != true)) {
                    this.PatternField = value;
                    this.RaisePropertyChanged("Pattern");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Begin {
            get {
                return this.BeginField;
            }
            set {
                if ((this.BeginField.Equals(value) != true)) {
                    this.BeginField = value;
                    this.RaisePropertyChanged("Begin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Discipline {
            get {
                return this.DisciplineField;
            }
            set {
                if ((object.ReferenceEquals(this.DisciplineField, value) != true)) {
                    this.DisciplineField = value;
                    this.RaisePropertyChanged("Discipline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Room {
            get {
                return this.RoomField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomField, value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsMoved {
            get {
                return this.IsMovedField;
            }
            set {
                if ((this.IsMovedField.Equals(value) != true)) {
                    this.IsMovedField = value;
                    this.RaisePropertyChanged("IsMoved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int PatternID {
            get {
                return this.PatternIDField;
            }
            set {
                if ((this.PatternIDField.Equals(value) != true)) {
                    this.PatternIDField = value;
                    this.RaisePropertyChanged("PatternID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepeatPatternInfo", Namespace="http://services.ist.ugtu.net/")]
    [System.SerializableAttribute()]
    public partial class RepeatPatternInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TypeField;
        
        private int FrequencyField;
        
        private int CountField;
        
        private System.DateTime BeginDateField;
        
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepeatMaskField;
        
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime BeginDate {
            get {
                return this.BeginDateField;
            }
            set {
                if ((this.BeginDateField.Equals(value) != true)) {
                    this.BeginDateField = value;
                    this.RaisePropertyChanged("BeginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RepeatMask {
            get {
                return this.RepeatMaskField;
            }
            set {
                if ((object.ReferenceEquals(this.RepeatMaskField, value) != true)) {
                    this.RepeatMaskField = value;
                    this.RaisePropertyChanged("RepeatMask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Сервис предоставления расписанияSoap", Namespace="http://services.ist.ugtu.net/", ConfigurationName="ScheduleServiceReference.СервиспредоставлениярасписанияSoap")]
    public interface СервиспредоставлениярасписанияSoap {
        
        // CODEGEN: Generating message contract since element name GetUGTUFacultiesResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetUGTUFaculties", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesResponse GetUGTUFaculties(ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUGTUSpecialtiesResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetAllUGTUSpecialties", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesResponse GetAllUGTUSpecialties(ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUGTUDepartmentsResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetAllUGTUDepartments", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsResponse GetAllUGTUDepartments(ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetUGTUSpecialtiesResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetUGTUSpecialties", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesResponse GetUGTUSpecialties(ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequest request);
        
        // CODEGEN: Generating message contract since element name GetUGTUDepartmentsResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetUGTUDepartments", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsResponse GetUGTUDepartments(ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetUGTUGroupsResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetUGTUGroups", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetUGTUGroupsResponse GetUGTUGroups(ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequest request);
        
        // CODEGEN: Generating message contract since element name GetUGTUTeachersResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetUGTUTeachers", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetUGTUTeachersResponse GetUGTUTeachers(ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequest request);
        
        // CODEGEN: Generating message contract since element name GetUGTULessonResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetUGTULesson", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetUGTULessonResponse GetUGTULesson(ConsoleTest.ScheduleServiceReference.GetUGTULessonRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUGTULessonsResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetAllUGTULessons", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsResponse GetAllUGTULessons(ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequest request);
        
        // CODEGEN: Generating message contract since element name GetEventsForGroupResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetEventsForGroup", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetEventsForGroupResponse GetEventsForGroup(ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequest request);
        
        // CODEGEN: Generating message contract since element name GetCalendarStringForGroupResult from namespace http://services.ist.ugtu.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.ist.ugtu.net/GetCalendarStringForGroup", ReplyAction="*")]
        ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupResponse GetCalendarStringForGroup(ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUFacultiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUFaculties", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequestBody Body;
        
        public GetUGTUFacultiesRequest() {
        }
        
        public GetUGTUFacultiesRequest(ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUGTUFacultiesRequestBody {
        
        public GetUGTUFacultiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUFacultiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUFacultiesResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesResponseBody Body;
        
        public GetUGTUFacultiesResponse() {
        }
        
        public GetUGTUFacultiesResponse(ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUFacultiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.FacInfo[] GetUGTUFacultiesResult;
        
        public GetUGTUFacultiesResponseBody() {
        }
        
        public GetUGTUFacultiesResponseBody(ConsoleTest.ScheduleServiceReference.FacInfo[] GetUGTUFacultiesResult) {
            this.GetUGTUFacultiesResult = GetUGTUFacultiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUGTUSpecialtiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUGTUSpecialties", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequestBody Body;
        
        public GetAllUGTUSpecialtiesRequest() {
        }
        
        public GetAllUGTUSpecialtiesRequest(ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUGTUSpecialtiesRequestBody {
        
        public GetAllUGTUSpecialtiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUGTUSpecialtiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUGTUSpecialtiesResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesResponseBody Body;
        
        public GetAllUGTUSpecialtiesResponse() {
        }
        
        public GetAllUGTUSpecialtiesResponse(ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetAllUGTUSpecialtiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.SpecInfo[] GetAllUGTUSpecialtiesResult;
        
        public GetAllUGTUSpecialtiesResponseBody() {
        }
        
        public GetAllUGTUSpecialtiesResponseBody(ConsoleTest.ScheduleServiceReference.SpecInfo[] GetAllUGTUSpecialtiesResult) {
            this.GetAllUGTUSpecialtiesResult = GetAllUGTUSpecialtiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUGTUDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUGTUDepartments", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequestBody Body;
        
        public GetAllUGTUDepartmentsRequest() {
        }
        
        public GetAllUGTUDepartmentsRequest(ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUGTUDepartmentsRequestBody {
        
        public GetAllUGTUDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUGTUDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUGTUDepartmentsResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsResponseBody Body;
        
        public GetAllUGTUDepartmentsResponse() {
        }
        
        public GetAllUGTUDepartmentsResponse(ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetAllUGTUDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.DepInfo[] GetAllUGTUDepartmentsResult;
        
        public GetAllUGTUDepartmentsResponseBody() {
        }
        
        public GetAllUGTUDepartmentsResponseBody(ConsoleTest.ScheduleServiceReference.DepInfo[] GetAllUGTUDepartmentsResult) {
            this.GetAllUGTUDepartmentsResult = GetAllUGTUDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUSpecialtiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUSpecialties", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequestBody Body;
        
        public GetUGTUSpecialtiesRequest() {
        }
        
        public GetUGTUSpecialtiesRequest(ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUSpecialtiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facID;
        
        public GetUGTUSpecialtiesRequestBody() {
        }
        
        public GetUGTUSpecialtiesRequestBody(int facID) {
            this.facID = facID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUSpecialtiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUSpecialtiesResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesResponseBody Body;
        
        public GetUGTUSpecialtiesResponse() {
        }
        
        public GetUGTUSpecialtiesResponse(ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUSpecialtiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.SpecInfo[] GetUGTUSpecialtiesResult;
        
        public GetUGTUSpecialtiesResponseBody() {
        }
        
        public GetUGTUSpecialtiesResponseBody(ConsoleTest.ScheduleServiceReference.SpecInfo[] GetUGTUSpecialtiesResult) {
            this.GetUGTUSpecialtiesResult = GetUGTUSpecialtiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUDepartments", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequestBody Body;
        
        public GetUGTUDepartmentsRequest() {
        }
        
        public GetUGTUDepartmentsRequest(ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUDepartmentsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int facID;
        
        public GetUGTUDepartmentsRequestBody() {
        }
        
        public GetUGTUDepartmentsRequestBody(int facID) {
            this.facID = facID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUDepartmentsResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsResponseBody Body;
        
        public GetUGTUDepartmentsResponse() {
        }
        
        public GetUGTUDepartmentsResponse(ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.DepInfo[] GetUGTUDepartmentsResult;
        
        public GetUGTUDepartmentsResponseBody() {
        }
        
        public GetUGTUDepartmentsResponseBody(ConsoleTest.ScheduleServiceReference.DepInfo[] GetUGTUDepartmentsResult) {
            this.GetUGTUDepartmentsResult = GetUGTUDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUGroups", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequestBody Body;
        
        public GetUGTUGroupsRequest() {
        }
        
        public GetUGTUGroupsRequest(ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUGroupsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SpecId;
        
        public GetUGTUGroupsRequestBody() {
        }
        
        public GetUGTUGroupsRequestBody(int SpecId) {
            this.SpecId = SpecId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUGroupsResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUGroupsResponseBody Body;
        
        public GetUGTUGroupsResponse() {
        }
        
        public GetUGTUGroupsResponse(ConsoleTest.ScheduleServiceReference.GetUGTUGroupsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUGroupsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.GroupInfo[] GetUGTUGroupsResult;
        
        public GetUGTUGroupsResponseBody() {
        }
        
        public GetUGTUGroupsResponseBody(ConsoleTest.ScheduleServiceReference.GroupInfo[] GetUGTUGroupsResult) {
            this.GetUGTUGroupsResult = GetUGTUGroupsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUTeachersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUTeachers", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequestBody Body;
        
        public GetUGTUTeachersRequest() {
        }
        
        public GetUGTUTeachersRequest(ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUTeachersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DepId;
        
        public GetUGTUTeachersRequestBody() {
        }
        
        public GetUGTUTeachersRequestBody(int DepId) {
            this.DepId = DepId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTUTeachersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTUTeachersResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTUTeachersResponseBody Body;
        
        public GetUGTUTeachersResponse() {
        }
        
        public GetUGTUTeachersResponse(ConsoleTest.ScheduleServiceReference.GetUGTUTeachersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTUTeachersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.TeacherInfo[] GetUGTUTeachersResult;
        
        public GetUGTUTeachersResponseBody() {
        }
        
        public GetUGTUTeachersResponseBody(ConsoleTest.ScheduleServiceReference.TeacherInfo[] GetUGTUTeachersResult) {
            this.GetUGTUTeachersResult = GetUGTUTeachersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTULessonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTULesson", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTULessonRequestBody Body;
        
        public GetUGTULessonRequest() {
        }
        
        public GetUGTULessonRequest(ConsoleTest.ScheduleServiceReference.GetUGTULessonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTULessonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LessonNum;
        
        public GetUGTULessonRequestBody() {
        }
        
        public GetUGTULessonRequestBody(int LessonNum) {
            this.LessonNum = LessonNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUGTULessonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUGTULessonResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetUGTULessonResponseBody Body;
        
        public GetUGTULessonResponse() {
        }
        
        public GetUGTULessonResponse(ConsoleTest.ScheduleServiceReference.GetUGTULessonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetUGTULessonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.LessonInfo GetUGTULessonResult;
        
        public GetUGTULessonResponseBody() {
        }
        
        public GetUGTULessonResponseBody(ConsoleTest.ScheduleServiceReference.LessonInfo GetUGTULessonResult) {
            this.GetUGTULessonResult = GetUGTULessonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUGTULessonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUGTULessons", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequestBody Body;
        
        public GetAllUGTULessonsRequest() {
        }
        
        public GetAllUGTULessonsRequest(ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUGTULessonsRequestBody {
        
        public GetAllUGTULessonsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUGTULessonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUGTULessonsResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsResponseBody Body;
        
        public GetAllUGTULessonsResponse() {
        }
        
        public GetAllUGTULessonsResponse(ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetAllUGTULessonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.LessonInfo[] GetAllUGTULessonsResult;
        
        public GetAllUGTULessonsResponseBody() {
        }
        
        public GetAllUGTULessonsResponseBody(ConsoleTest.ScheduleServiceReference.LessonInfo[] GetAllUGTULessonsResult) {
            this.GetAllUGTULessonsResult = GetAllUGTULessonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsForGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsForGroup", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequestBody Body;
        
        public GetEventsForGroupRequest() {
        }
        
        public GetEventsForGroupRequest(ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetEventsForGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int groupId;
        
        public GetEventsForGroupRequestBody() {
        }
        
        public GetEventsForGroupRequestBody(int groupId) {
            this.groupId = groupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEventsForGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEventsForGroupResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetEventsForGroupResponseBody Body;
        
        public GetEventsForGroupResponse() {
        }
        
        public GetEventsForGroupResponse(ConsoleTest.ScheduleServiceReference.GetEventsForGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetEventsForGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleTest.ScheduleServiceReference.EventInfo[] GetEventsForGroupResult;
        
        public GetEventsForGroupResponseBody() {
        }
        
        public GetEventsForGroupResponseBody(ConsoleTest.ScheduleServiceReference.EventInfo[] GetEventsForGroupResult) {
            this.GetEventsForGroupResult = GetEventsForGroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalendarStringForGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalendarStringForGroup", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequestBody Body;
        
        public GetCalendarStringForGroupRequest() {
        }
        
        public GetCalendarStringForGroupRequest(ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetCalendarStringForGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GroupID;
        
        public GetCalendarStringForGroupRequestBody() {
        }
        
        public GetCalendarStringForGroupRequestBody(int GroupID) {
            this.GroupID = GroupID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalendarStringForGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalendarStringForGroupResponse", Namespace="http://services.ist.ugtu.net/", Order=0)]
        public ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupResponseBody Body;
        
        public GetCalendarStringForGroupResponse() {
        }
        
        public GetCalendarStringForGroupResponse(ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class GetCalendarStringForGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCalendarStringForGroupResult;
        
        public GetCalendarStringForGroupResponseBody() {
        }
        
        public GetCalendarStringForGroupResponseBody(string GetCalendarStringForGroupResult) {
            this.GetCalendarStringForGroupResult = GetCalendarStringForGroupResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface СервиспредоставлениярасписанияSoapChannel : ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class СервиспредоставлениярасписанияSoapClient : System.ServiceModel.ClientBase<ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap>, ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap {
        
        public СервиспредоставлениярасписанияSoapClient() {
        }
        
        public СервиспредоставлениярасписанияSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public СервиспредоставлениярасписанияSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public СервиспредоставлениярасписанияSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public СервиспредоставлениярасписанияSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetUGTUFaculties(ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequest request) {
            return base.Channel.GetUGTUFaculties(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.FacInfo[] GetUGTUFaculties() {
            ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequest inValue = new ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesRequestBody();
            ConsoleTest.ScheduleServiceReference.GetUGTUFacultiesResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetUGTUFaculties(inValue);
            return retVal.Body.GetUGTUFacultiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetAllUGTUSpecialties(ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequest request) {
            return base.Channel.GetAllUGTUSpecialties(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.SpecInfo[] GetAllUGTUSpecialties() {
            ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequest inValue = new ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesRequestBody();
            ConsoleTest.ScheduleServiceReference.GetAllUGTUSpecialtiesResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetAllUGTUSpecialties(inValue);
            return retVal.Body.GetAllUGTUSpecialtiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetAllUGTUDepartments(ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequest request) {
            return base.Channel.GetAllUGTUDepartments(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.DepInfo[] GetAllUGTUDepartments() {
            ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequest inValue = new ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsRequestBody();
            ConsoleTest.ScheduleServiceReference.GetAllUGTUDepartmentsResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetAllUGTUDepartments(inValue);
            return retVal.Body.GetAllUGTUDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetUGTUSpecialties(ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequest request) {
            return base.Channel.GetUGTUSpecialties(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.SpecInfo[] GetUGTUSpecialties(int facID) {
            ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequest inValue = new ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesRequestBody();
            inValue.Body.facID = facID;
            ConsoleTest.ScheduleServiceReference.GetUGTUSpecialtiesResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetUGTUSpecialties(inValue);
            return retVal.Body.GetUGTUSpecialtiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetUGTUDepartments(ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequest request) {
            return base.Channel.GetUGTUDepartments(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.DepInfo[] GetUGTUDepartments(int facID) {
            ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequest inValue = new ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsRequestBody();
            inValue.Body.facID = facID;
            ConsoleTest.ScheduleServiceReference.GetUGTUDepartmentsResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetUGTUDepartments(inValue);
            return retVal.Body.GetUGTUDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetUGTUGroupsResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetUGTUGroups(ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequest request) {
            return base.Channel.GetUGTUGroups(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.GroupInfo[] GetUGTUGroups(int SpecId) {
            ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequest inValue = new ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetUGTUGroupsRequestBody();
            inValue.Body.SpecId = SpecId;
            ConsoleTest.ScheduleServiceReference.GetUGTUGroupsResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetUGTUGroups(inValue);
            return retVal.Body.GetUGTUGroupsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetUGTUTeachersResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetUGTUTeachers(ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequest request) {
            return base.Channel.GetUGTUTeachers(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.TeacherInfo[] GetUGTUTeachers(int DepId) {
            ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequest inValue = new ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetUGTUTeachersRequestBody();
            inValue.Body.DepId = DepId;
            ConsoleTest.ScheduleServiceReference.GetUGTUTeachersResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetUGTUTeachers(inValue);
            return retVal.Body.GetUGTUTeachersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetUGTULessonResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetUGTULesson(ConsoleTest.ScheduleServiceReference.GetUGTULessonRequest request) {
            return base.Channel.GetUGTULesson(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.LessonInfo GetUGTULesson(int LessonNum) {
            ConsoleTest.ScheduleServiceReference.GetUGTULessonRequest inValue = new ConsoleTest.ScheduleServiceReference.GetUGTULessonRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetUGTULessonRequestBody();
            inValue.Body.LessonNum = LessonNum;
            ConsoleTest.ScheduleServiceReference.GetUGTULessonResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetUGTULesson(inValue);
            return retVal.Body.GetUGTULessonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetAllUGTULessons(ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequest request) {
            return base.Channel.GetAllUGTULessons(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.LessonInfo[] GetAllUGTULessons() {
            ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequest inValue = new ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsRequestBody();
            ConsoleTest.ScheduleServiceReference.GetAllUGTULessonsResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetAllUGTULessons(inValue);
            return retVal.Body.GetAllUGTULessonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetEventsForGroupResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetEventsForGroup(ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequest request) {
            return base.Channel.GetEventsForGroup(request);
        }
        
        public ConsoleTest.ScheduleServiceReference.EventInfo[] GetEventsForGroup(int groupId) {
            ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequest inValue = new ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetEventsForGroupRequestBody();
            inValue.Body.groupId = groupId;
            ConsoleTest.ScheduleServiceReference.GetEventsForGroupResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetEventsForGroup(inValue);
            return retVal.Body.GetEventsForGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupResponse ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap.GetCalendarStringForGroup(ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequest request) {
            return base.Channel.GetCalendarStringForGroup(request);
        }
        
        public string GetCalendarStringForGroup(int GroupID) {
            ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequest inValue = new ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequest();
            inValue.Body = new ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupRequestBody();
            inValue.Body.GroupID = GroupID;
            ConsoleTest.ScheduleServiceReference.GetCalendarStringForGroupResponse retVal = ((ConsoleTest.ScheduleServiceReference.СервиспредоставлениярасписанияSoap)(this)).GetCalendarStringForGroup(inValue);
            return retVal.Body.GetCalendarStringForGroupResult;
        }
    }
}
