<?xml version="1.0" encoding="utf-8"?><Database Name="UGTU" Class="ScheduleDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ugtudb.ugtu.net;Initial Catalog=UGTU;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="UGTUConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SheduleEvent" Member="SheduleEvents">
    <Type Name="SheduleEvent">
      <Column Name="ik_event" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_shedule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_id_prepod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_event_type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ik_room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bit_exception" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ik_repeat_pattern" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dBegin_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="i_version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SheduleEvent_SheduleEventException" Member="SheduleEventExceptions" ThisKey="ik_event" OtherKey="ik_old_event" Type="SheduleEventException" />
      <Association Name="SheduleEvent_SheduleEventException1" Member="SheduleEventExceptions1" ThisKey="ik_event" OtherKey="ik_new_event" Type="SheduleEventException" />
      <Association Name="SheduleEvent_Relation_event_plan_nagr" Member="Relation_event_plan_nagrs" ThisKey="ik_event" OtherKey="ik_event" Type="Relation_event_plan_nagr" />
      <Association Name="SheduleEventType_SheduleEvent" Member="SheduleEventType" ThisKey="ik_event_type" OtherKey="ik_event_type" Type="SheduleEventType" IsForeignKey="true" />
      <Association Name="Shedule_SheduleEvent" Member="Shedule" ThisKey="ik_shedule" OtherKey="ik_shedule" Type="Shedule" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="RepeatPattern_SheduleEvent" Member="RepeatPattern" ThisKey="ik_repeat_pattern" OtherKey="ik_repeat_pattern" Type="RepeatPattern" IsForeignKey="true" />
      <Association Name="Relation_kafedra_prep_SheduleEvent" Member="Relation_kafedra_prep" ThisKey="ik_id_prepod" OtherKey="ik_id_prepod" Type="Relation_kafedra_prep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SheduleExamination" Member="SheduleExaminations">
    <Type Name="SheduleExamination">
      <Column Name="ik_examination" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dt_time_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dt_time_stop" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ik_shedule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_id_prepod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="i_version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SheduleExamination_Relation_exam_plan_nagr" Member="Relation_exam_plan_nagrs" ThisKey="ik_examination" OtherKey="ik_examination" Type="Relation_exam_plan_nagr" />
      <Association Name="Shedule_SheduleExamination" Member="Shedule" ThisKey="ik_shedule" OtherKey="ik_shedule" Type="Shedule" IsForeignKey="true" />
      <Association Name="Relation_kafedra_prep_SheduleExamination" Member="Relation_kafedra_prep" ThisKey="ik_id_prepod" OtherKey="ik_id_prepod" Type="Relation_kafedra_prep" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SheduleEventException" Member="SheduleEventExceptions">
    <Type Name="SheduleEventException">
      <Column Name="ik_old_event" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ik_new_event" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dExceptionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SheduleEvent_SheduleEventException" Member="SheduleEvent" ThisKey="ik_old_event" OtherKey="ik_event" Type="SheduleEvent" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="SheduleEvent_SheduleEventException1" Member="SheduleEvent1" ThisKey="ik_new_event" OtherKey="ik_event" Type="SheduleEvent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SheduleEventType" Member="SheduleEventTypes">
    <Type Name="SheduleEventType">
      <Column Name="ik_event_type" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cName_event" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dEvent_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dEvent_stop" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="SheduleEventType_SheduleEvent" Member="SheduleEvents" ThisKey="ik_event_type" OtherKey="ik_event_type" Type="SheduleEvent" />
    </Type>
  </Table>
  <Table Name="dbo.Shedule" Member="Shedules">
    <Type Name="Shedule">
      <Column Name="ik_shedule" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_sem_type" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="d_sem_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="d_sem_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="d_session_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="d_session_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="d_work_time_end" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="d_work_time_start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Shedule_SheduleEvent" Member="SheduleEvents" ThisKey="ik_shedule" OtherKey="ik_shedule" Type="SheduleEvent" />
      <Association Name="Shedule_SheduleExamination" Member="SheduleExaminations" ThisKey="ik_shedule" OtherKey="ik_shedule" Type="SheduleExamination" />
      <Association Name="Year_uch_pl_Shedule" Member="Year_uch_pl" ThisKey="ik_year" OtherKey="ik_year_uch_pl" Type="Year_uch_pl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_event_plan_nagr" Member="Relation_event_plan_nagrs">
    <Type Name="Relation_event_plan_nagr">
      <Column Name="ik_event" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ik_prepod_plan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="SheduleEvent_Relation_event_plan_nagr" Member="SheduleEvent" ThisKey="ik_event" OtherKey="ik_event" Type="SheduleEvent" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Prepod_plan_nagr_Relation_event_plan_nagr" Member="Prepod_plan_nagr" ThisKey="ik_prepod_plan" OtherKey="ik_prepod_plan" Type="Prepod_plan_nagr" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_exam_plan_nagr" Member="Relation_exam_plan_nagrs">
    <Type Name="Relation_exam_plan_nagr">
      <Column Name="ik_examination" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ik_prepod_plan" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="SheduleExamination_Relation_exam_plan_nagr" Member="SheduleExamination" ThisKey="ik_examination" OtherKey="ik_examination" Type="SheduleExamination" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Prepod_plan_nagr_Relation_exam_plan_nagr" Member="Prepod_plan_nagr" ThisKey="ik_prepod_plan" OtherKey="ik_prepod_plan" Type="Prepod_plan_nagr" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_calc_unit_grup" Member="Relation_calc_unit_grups">
    <Type Name="Relation_calc_unit_grup">
      <Column Name="ik_grup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_calc_unit" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Calc_unit_Relation_calc_unit_grup" Member="Calc_unit" ThisKey="ik_calc_unit" OtherKey="ik_calc_unit" Type="Calc_unit" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Grup_Relation_calc_unit_grup" Member="Grup" ThisKey="ik_grup" OtherKey="Ik_grup" Type="Grup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prepod_plan_nagr" Member="Prepod_plan_nagrs">
    <Type Name="Prepod_plan_nagr">
      <Column Name="ik_prepod_plan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_content_plan_nagr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="f_hour_per_unit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="i_student_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_calc_unit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="by_plan_number" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ik_id_prepod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="commission_member" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Prepod_plan_nagr_Relation_event_plan_nagr" Member="Relation_event_plan_nagrs" ThisKey="ik_prepod_plan" OtherKey="ik_prepod_plan" Type="Relation_event_plan_nagr" />
      <Association Name="Prepod_plan_nagr_Relation_exam_plan_nagr" Member="Relation_exam_plan_nagrs" ThisKey="ik_prepod_plan" OtherKey="ik_prepod_plan" Type="Relation_exam_plan_nagr" />
      <Association Name="Calc_unit_Prepod_plan_nagr" Member="Calc_unit" ThisKey="ik_calc_unit" OtherKey="ik_calc_unit" Type="Calc_unit" IsForeignKey="true" />
      <Association Name="Content_plan_nagr_Prepod_plan_nagr" Member="Content_plan_nagr" ThisKey="ik_content_plan_nagr" OtherKey="ik_content_plan_nagr" Type="Content_plan_nagr" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Relation_kafedra_prep_Prepod_plan_nagr" Member="Relation_kafedra_prep" ThisKey="ik_id_prepod" OtherKey="ik_id_prepod" Type="Relation_kafedra_prep" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RepeatPattern" Member="RepeatPatterns">
    <Type Name="RepeatPattern">
      <Column Name="ik_repeat_pattern" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_repeat_type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="iRepeat_frequency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cRepeat_mask" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ik_repeat_limit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="iRepeat_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dFinal_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="RepeatPattern_SheduleEvent" Member="SheduleEvents" ThisKey="ik_repeat_pattern" OtherKey="ik_repeat_pattern" Type="SheduleEvent" />
      <Association Name="RepeatLimit_RepeatPattern" Member="RepeatLimit" ThisKey="ik_repeat_limit" OtherKey="ik_repeat_limit" Type="RepeatLimit" IsForeignKey="true" />
      <Association Name="RepeatType_RepeatPattern" Member="RepeatType" ThisKey="ik_repeat_type" OtherKey="ik_repeat_type" Type="RepeatType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RepeatLimit" Member="RepeatLimits">
    <Type Name="RepeatLimit">
      <Column Name="ik_repeat_limit" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cname_repeat_limit" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RepeatLimit_RepeatPattern" Member="RepeatPatterns" ThisKey="ik_repeat_limit" OtherKey="ik_repeat_limit" Type="RepeatPattern" />
    </Type>
  </Table>
  <Table Name="dbo.Calc_unit" Member="Calc_units">
    <Type Name="Calc_unit">
      <Column Name="ik_calc_unit" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cName_calc_unit" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ik_shema_of_potok" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_uch_plan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Calc_unit_Relation_calc_unit_grup" Member="Relation_calc_unit_grup" ThisKey="ik_calc_unit" OtherKey="ik_calc_unit" Type="Relation_calc_unit_grup" Cardinality="One" />
      <Association Name="Calc_unit_Prepod_plan_nagr" Member="Prepod_plan_nagrs" ThisKey="ik_calc_unit" OtherKey="ik_calc_unit" Type="Prepod_plan_nagr" />
      <Association Name="Potok_shema_Calc_unit" Member="Potok_shema" ThisKey="ik_shema_of_potok" OtherKey="ik_shema_of_potok" Type="Potok_shema" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Content_plan_nagr" Member="Content_plan_nagrs">
    <Type Name="Content_plan_nagr">
      <Column Name="ik_content_plan_nagr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_plan_nagr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_disc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_vid_zanyat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_shema_of_potok" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_vid_nagruzki" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="i_commission_count" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Content_plan_nagr_Prepod_plan_nagr" Member="Prepod_plan_nagrs" ThisKey="ik_content_plan_nagr" OtherKey="ik_content_plan_nagr" Type="Prepod_plan_nagr" />
      <Association Name="Potok_shema_Content_plan_nagr" Member="Potok_shema" ThisKey="ik_shema_of_potok" OtherKey="ik_shema_of_potok" Type="Potok_shema" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Potok" Member="Potoks">
    <Type Name="Potok">
      <Column Name="ik_potok" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cname_potok" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="ik_norm_of_time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_uch_plan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_year_enter" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Potok_Potok_shema" Member="Potok_shemas" ThisKey="ik_potok" OtherKey="ik_potok" Type="Potok_shema" />
      <Association Name="Potok_Relation_potok_grup" Member="Relation_potok_grups" ThisKey="ik_potok" OtherKey="ik_potok" Type="Relation_potok_grup" />
      <Association Name="Potok_Relation_potok_spec" Member="Relation_potok_specs" ThisKey="ik_potok" OtherKey="ik_potok" Type="Relation_potok_spec" />
      <Association Name="Year_uch_pl_Potok" Member="Year_uch_pl" ThisKey="ik_year_enter" OtherKey="ik_year_uch_pl" Type="Year_uch_pl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Potok_shema" Member="Potok_shemas">
    <Type Name="Potok_shema">
      <Column Name="ik_shema_of_potok" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_potok" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_decompose_type" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="cName_shema" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Potok_shema_Calc_unit" Member="Calc_units" ThisKey="ik_shema_of_potok" OtherKey="ik_shema_of_potok" Type="Calc_unit" />
      <Association Name="Potok_shema_Content_plan_nagr" Member="Content_plan_nagrs" ThisKey="ik_shema_of_potok" OtherKey="ik_shema_of_potok" Type="Content_plan_nagr" />
      <Association Name="Potok_Potok_shema" Member="Potok" ThisKey="ik_potok" OtherKey="ik_potok" Type="Potok" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Shema_decompose_Potok_shema" Member="Shema_decompose" ThisKey="ik_decompose_type" OtherKey="ik_decompose_type" Type="Shema_decompose" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Shema_decompose" Member="Shema_decomposes">
    <Type Name="Shema_decompose">
      <Column Name="ik_decompose_type" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cName_decompose" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Shema_decompose_Potok_shema" Member="Potok_shemas" ThisKey="ik_decompose_type" OtherKey="ik_decompose_type" Type="Potok_shema" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_potok_grup" Member="Relation_potok_grups">
    <Type Name="Relation_potok_grup">
      <Column Name="ik_potok" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ik_grup" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Potok_Relation_potok_grup" Member="Potok" ThisKey="ik_potok" OtherKey="ik_potok" Type="Potok" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Grup_Relation_potok_grup" Member="Grup" ThisKey="ik_grup" OtherKey="Ik_grup" Type="Grup" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Grup" Member="Grups">
    <Type Name="Grup">
      <Column Name="Ik_grup" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_spec_fac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cname_grup" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ik_uch_plan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nYear_post" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Grup_Relation_calc_unit_grup" Member="Relation_calc_unit_grups" ThisKey="Ik_grup" OtherKey="ik_grup" Type="Relation_calc_unit_grup" />
      <Association Name="Grup_Relation_potok_grup" Member="Relation_potok_grups" ThisKey="Ik_grup" OtherKey="ik_grup" Type="Relation_potok_grup" />
      <Association Name="Relation_spec_fac_Grup" Member="Relation_spec_fac" ThisKey="ik_spec_fac" OtherKey="ik_spec_fac" Type="Relation_spec_fac" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prepod" Member="Prepods">
    <Type Name="Prepod">
      <Column Name="itab_n" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_rank" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_degree" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="prepLogin" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="nCode" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="Prepod_Relation_kafedra_prep" Member="Relation_kafedra_preps" ThisKey="itab_n" OtherKey="itab_n" Type="Relation_kafedra_prep" />
      <Association Name="Person_Prepod" Member="Person" ThisKey="nCode" OtherKey="nCode" Type="Person" IsForeignKey="true" />
      <Association Name="PrepodRank_Prepod" Member="PrepodRank" ThisKey="ik_rank" OtherKey="ik_rank" Type="PrepodRank" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_kafedra_prep" Member="Relation_kafedra_preps">
    <Type Name="Relation_kafedra_prep">
      <Column Name="ik_kaf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="itab_n" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_work_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_capacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_defence_fund" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="f_rates" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ik_id_prepod" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="release_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Relation_kafedra_prep_SheduleEvent" Member="SheduleEvents" ThisKey="ik_id_prepod" OtherKey="ik_id_prepod" Type="SheduleEvent" />
      <Association Name="Relation_kafedra_prep_SheduleExamination" Member="SheduleExaminations" ThisKey="ik_id_prepod" OtherKey="ik_id_prepod" Type="SheduleExamination" />
      <Association Name="Relation_kafedra_prep_Prepod_plan_nagr" Member="Prepod_plan_nagrs" ThisKey="ik_id_prepod" OtherKey="ik_id_prepod" Type="Prepod_plan_nagr" />
      <Association Name="Prepod_Relation_kafedra_prep" Member="Prepod" ThisKey="itab_n" OtherKey="itab_n" Type="Prepod" IsForeignKey="true" />
      <Association Name="kafedra_Relation_kafedra_prep" Member="kafedra" ThisKey="ik_kaf" OtherKey="ik_kaf" Type="kafedra" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="nCode" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Clastname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Cfirstname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Cotch" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Dd_birth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cplacebirth" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Linval" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ldeti" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lrab" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lSex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Lobchegit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cSotTel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ctelefon" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Ik_grazd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ik_nac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ik_sem_pol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cInn" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cStrax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ik_voen_zvanie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="itab_n" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Person_Prepod" Member="Prepods" ThisKey="nCode" OtherKey="nCode" Type="Prepod" />
    </Type>
  </Table>
  <Table Name="dbo.Fac" Member="Facs">
    <Type Name="Fac">
      <Column Name="Ik_fac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cname_fac" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cshort_name_fac" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fDateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bit_calc_nagr" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Fac_Relation_spec_fac" Member="Relation_spec_facs" ThisKey="Ik_fac" OtherKey="ik_fac" Type="Relation_spec_fac" />
      <Association Name="Fac_kafedra" Member="kafedras" ThisKey="Ik_fac" OtherKey="ik_fac" Type="kafedra" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_spec_fac" Member="Relation_spec_facs">
    <Type Name="Relation_spec_fac">
      <Column Name="ik_spec_fac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_spec" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_fac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YearObuch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_rule" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ik_form_ed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_kat_zaved" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Relation_spec_fac_Grup" Member="Grups" ThisKey="ik_spec_fac" OtherKey="ik_spec_fac" Type="Grup" />
      <Association Name="Relation_spec_fac_Relation_potok_spec" Member="Relation_potok_specs" ThisKey="ik_spec_fac" OtherKey="ik_spec_fac" Type="Relation_potok_spec" />
      <Association Name="Fac_Relation_spec_fac" Member="Fac" ThisKey="ik_fac" OtherKey="Ik_fac" Type="Fac" IsForeignKey="true" />
      <Association Name="Spec_stud_Relation_spec_fac" Member="Spec_stud" ThisKey="ik_spec" OtherKey="ik_spec" Type="Spec_stud" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Spec_stud" Member="Spec_studs">
    <Type Name="Spec_stud">
      <Column Name="ik_spec" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cname_spec" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Cshort_spec" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Sh_spec" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ik_direction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ik_vip_dep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dDate_spec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="nN_prikaz" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="spDateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cname_qualif" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Spec_stud_Relation_spec_fac" Member="Relation_spec_facs" ThisKey="ik_spec" OtherKey="ik_spec" Type="Relation_spec_fac" />
    </Type>
  </Table>
  <Table Name="dbo.kafedra" Member="kafedras">
    <Type Name="kafedra">
      <Column Name="ik_kaf" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ik_fac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cname_kaf" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cshort_name_kaf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="kolvo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="kDateExit" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="kafedra_Relation_kafedra_prep" Member="Relation_kafedra_preps" ThisKey="ik_kaf" OtherKey="ik_kaf" Type="Relation_kafedra_prep" />
      <Association Name="Fac_kafedra" Member="Fac" ThisKey="ik_fac" OtherKey="Ik_fac" Type="Fac" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PrepodRank" Member="PrepodRanks">
    <Type Name="PrepodRank">
      <Column Name="ik_rank" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cName_rank" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PrepodRank_Prepod" Member="Prepods" ThisKey="ik_rank" OtherKey="ik_rank" Type="Prepod" />
    </Type>
  </Table>
  <Table Name="dbo.RepeatType" Member="RepeatTypes">
    <Type Name="RepeatType">
      <Column Name="ik_repeat_type" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cName_repeat_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="RepeatType_RepeatPattern" Member="RepeatPatterns" ThisKey="ik_repeat_type" OtherKey="ik_repeat_type" Type="RepeatPattern" />
    </Type>
  </Table>
  <Table Name="dbo.SheduleEventWithPlanNagr" Member="SheduleEventWithPlanNagrs">
    <Type Name="SheduleEventWithPlanNagr">
      <Column Name="ik_event" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_shedule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="i_version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_id_prepod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_room" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_event_type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ik_repeat_pattern" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_repeat_type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="iRepeat_frequency" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cRepeat_mask" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ik_repeat_limit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="iRepeat_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dFinal_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dBegin_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dt_time_start" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dt_time_stop" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ik_disc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cName_disc" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ik_vid_zanyat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cName_vid_zanyat" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ik_vid_nagruzki" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Сname_vid_nagruzki_short" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ik_calc_unit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cName_calc_unit" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ik_decompose_type" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ik_potok" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_grup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_fac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ik_id_plan_prepod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_kaf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ik_form_ed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="clastname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cfirstname" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cotch" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="itab_n" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cName_work_type_short" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Cname_room" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CName_campus" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="except_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relation_potok_spec" Member="Relation_potok_specs">
    <Type Name="Relation_potok_spec">
      <Column Name="ik_potok" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ik_spec_fac" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Potok_Relation_potok_spec" Member="Potok" ThisKey="ik_potok" OtherKey="ik_potok" Type="Potok" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Relation_spec_fac_Relation_potok_spec" Member="Relation_spec_fac" ThisKey="ik_spec_fac" OtherKey="ik_spec_fac" Type="Relation_spec_fac" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Year_uch_pl" Member="Year_uch_pls">
    <Type Name="Year_uch_pl">
      <Column Name="ik_year_uch_pl" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="year_value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Year_uch_pl_Shedule" Member="Shedules" ThisKey="ik_year_uch_pl" OtherKey="ik_year" Type="Shedule" />
      <Association Name="Year_uch_pl_Potok" Member="Potoks" ThisKey="ik_year_uch_pl" OtherKey="ik_year_enter" Type="Potok" />
    </Type>
  </Table>
</Database>