//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UGTU_Service_Client.net.ugtu.ist.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StudentProgressServiceSoap", Namespace="http://services.ist.ugtu.net/")]
    public partial class StudentProgressService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStudentProgressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StudentProgressService() {
            this.Url = global::UGTU_Service_Client.Properties.Settings.Default.UGTU_Service_Client_net_ugtu_ist_services_StudentProgressService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStudentProgressCompletedEventHandler GetStudentProgressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.ist.ugtu.net/GetStudentProgress", RequestNamespace="http://services.ist.ugtu.net/", ResponseNamespace="http://services.ist.ugtu.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StudentProgressDTO GetStudentProgress(string StudentID, string PasportNum) {
            object[] results = this.Invoke("GetStudentProgress", new object[] {
                        StudentID,
                        PasportNum});
            return ((StudentProgressDTO)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentProgressAsync(string StudentID, string PasportNum) {
            this.GetStudentProgressAsync(StudentID, PasportNum, null);
        }
        
        /// <remarks/>
        public void GetStudentProgressAsync(string StudentID, string PasportNum, object userState) {
            if ((this.GetStudentProgressOperationCompleted == null)) {
                this.GetStudentProgressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentProgressOperationCompleted);
            }
            this.InvokeAsync("GetStudentProgress", new object[] {
                        StudentID,
                        PasportNum}, this.GetStudentProgressOperationCompleted, userState);
        }
        
        private void OnGetStudentProgressOperationCompleted(object arg) {
            if ((this.GetStudentProgressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentProgressCompleted(this, new GetStudentProgressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class StudentProgressDTO {
        
        private string idField;
        
        private string currentStatusField;
        
        private SemesterInfo[] semestersField;
        
        private ThesisWorkInfo thesisField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CurrentStatus {
            get {
                return this.currentStatusField;
            }
            set {
                this.currentStatusField = value;
            }
        }
        
        /// <remarks/>
        public SemesterInfo[] Semesters {
            get {
                return this.semestersField;
            }
            set {
                this.semestersField = value;
            }
        }
        
        /// <remarks/>
        public ThesisWorkInfo Thesis {
            get {
                return this.thesisField;
            }
            set {
                this.thesisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class SemesterInfo {
        
        private int semesterNumField;
        
        private System.DateTime semesterStartDateField;
        
        private System.DateTime semesterEndDateField;
        
        private System.DateTime sessionStartDateField;
        
        private System.DateTime sessionEndDateField;
        
        private ProgressInfo[] progressField;
        
        private CheckPointInfo[] checkPointsField;
        
        private StudentSemesterProlong prolongField;
        
        /// <remarks/>
        public int SemesterNum {
            get {
                return this.semesterNumField;
            }
            set {
                this.semesterNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SemesterStartDate {
            get {
                return this.semesterStartDateField;
            }
            set {
                this.semesterStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SemesterEndDate {
            get {
                return this.semesterEndDateField;
            }
            set {
                this.semesterEndDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SessionStartDate {
            get {
                return this.sessionStartDateField;
            }
            set {
                this.sessionStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SessionEndDate {
            get {
                return this.sessionEndDateField;
            }
            set {
                this.sessionEndDateField = value;
            }
        }
        
        /// <remarks/>
        public ProgressInfo[] Progress {
            get {
                return this.progressField;
            }
            set {
                this.progressField = value;
            }
        }
        
        /// <remarks/>
        public CheckPointInfo[] CheckPoints {
            get {
                return this.checkPointsField;
            }
            set {
                this.checkPointsField = value;
            }
        }
        
        /// <remarks/>
        public StudentSemesterProlong Prolong {
            get {
                return this.prolongField;
            }
            set {
                this.prolongField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class ProgressInfo {
        
        private string disciplineField;
        
        private string lessonTypeField;
        
        private string markField;
        
        private System.DateTime passDateField;
        
        private System.DateTime planDateField;
        
        /// <remarks/>
        public string Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        public string LessonType {
            get {
                return this.lessonTypeField;
            }
            set {
                this.lessonTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Mark {
            get {
                return this.markField;
            }
            set {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PassDate {
            get {
                return this.passDateField;
            }
            set {
                this.passDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PlanDate {
            get {
                return this.planDateField;
            }
            set {
                this.planDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class ThesisWorkInfo {
        
        private string thesisMarkField;
        
        private string thesisTypeField;
        
        private string thesisTitleField;
        
        private System.DateTime thesisDateField;
        
        private string holderField;
        
        /// <remarks/>
        public string ThesisMark {
            get {
                return this.thesisMarkField;
            }
            set {
                this.thesisMarkField = value;
            }
        }
        
        /// <remarks/>
        public string ThesisType {
            get {
                return this.thesisTypeField;
            }
            set {
                this.thesisTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ThesisTitle {
            get {
                return this.thesisTitleField;
            }
            set {
                this.thesisTitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ThesisDate {
            get {
                return this.thesisDateField;
            }
            set {
                this.thesisDateField = value;
            }
        }
        
        /// <remarks/>
        public string Holder {
            get {
                return this.holderField;
            }
            set {
                this.holderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class StudentSemesterProlong {
        
        private System.DateTime prolongToField;
        
        private string prolongReasonField;
        
        /// <remarks/>
        public System.DateTime ProlongTo {
            get {
                return this.prolongToField;
            }
            set {
                this.prolongToField = value;
            }
        }
        
        /// <remarks/>
        public string ProlongReason {
            get {
                return this.prolongReasonField;
            }
            set {
                this.prolongReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class CheckDisciplinePointInfo {
        
        private string disciplineField;
        
        private bool hasPassedField;
        
        private int absentHoursField;
        
        private int absentByReasonHoursField;
        
        /// <remarks/>
        public string Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        public bool HasPassed {
            get {
                return this.hasPassedField;
            }
            set {
                this.hasPassedField = value;
            }
        }
        
        /// <remarks/>
        public int AbsentHours {
            get {
                return this.absentHoursField;
            }
            set {
                this.absentHoursField = value;
            }
        }
        
        /// <remarks/>
        public int AbsentByReasonHours {
            get {
                return this.absentByReasonHoursField;
            }
            set {
                this.absentByReasonHoursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.ist.ugtu.net/")]
    public partial class CheckPointInfo {
        
        private CheckDisciplinePointInfo[] disciplinesField;
        
        private int checkPointNumField;
        
        private System.DateTime checkPointStartDateField;
        
        private System.DateTime checkPointEndDateField;
        
        /// <remarks/>
        public CheckDisciplinePointInfo[] Disciplines {
            get {
                return this.disciplinesField;
            }
            set {
                this.disciplinesField = value;
            }
        }
        
        /// <remarks/>
        public int CheckPointNum {
            get {
                return this.checkPointNumField;
            }
            set {
                this.checkPointNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CheckPointStartDate {
            get {
                return this.checkPointStartDateField;
            }
            set {
                this.checkPointStartDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CheckPointEndDate {
            get {
                return this.checkPointEndDateField;
            }
            set {
                this.checkPointEndDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetStudentProgressCompletedEventHandler(object sender, GetStudentProgressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentProgressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentProgressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StudentProgressDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StudentProgressDTO)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591