unit TestuAbitZachislenieController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, uAbitZachislenieController, Windows, Forms, GeneralController, ComObj,
  SysUtils, ADODB, uDM, StdCtrls, uJoinGroup, ApplicationController, Messages, DBGrids,
  DBLookupEh, ABIT_zachislenie_frame, Controls, Classes, Dialogs, ExcelXP, Grids, DB, 
  Variants, Graphics, DBGridEh;
type
  // Test methods for class TAbitZachislenieController

  TestTAbitZachislenieController = class(TTestCase)
  strict private
    FAbitZachislenieController: TAbitZachislenieController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAbit_IsOldZachNewZach;
    procedure TestAbit_IsOldZachOldZach;
    procedure TestAbit_IsOldZachTooLongZach;
    procedure TestAbit_IsOldZachNullZach;
    procedure TestAbit_IsOldZachTooShortZach;
  end;

implementation


procedure TestTAbitZachislenieController.SetUp;
begin
  //FAbitZachislenieController := TAbitZachislenieController.Create;

end;

procedure TestTAbitZachislenieController.TearDown;
begin
  //FAbitZachislenieController.Free;
  //FAbitZachislenieController := nil;
end;

procedure TestTAbitZachislenieController.TestAbit_IsOldZachNewZach;
const TestNumZach: string = '000000';
begin
  CheckTrue(not TAbitZachislenieController.Instance.Abit_IsOldZach(TestNumZach));
end;

procedure TestTAbitZachislenieController.TestAbit_IsOldZachNullZach;
begin
  CheckTrue(not TAbitZachislenieController.Instance.Abit_IsOldZach(''));
end;

procedure TestTAbitZachislenieController.TestAbit_IsOldZachOldZach;
const TestNumZach: string = '100000';
begin
  CheckTrue(TAbitZachislenieController.Instance.Abit_IsOldZach('100000'));
end;

procedure TestTAbitZachislenieController.TestAbit_IsOldZachTooLongZach;
begin
  CheckTrue(not TAbitZachislenieController.Instance.Abit_IsOldZach('10000000000'));
end;

procedure TestTAbitZachislenieController.TestAbit_IsOldZachTooShortZach;
begin
  CheckTrue(not TAbitZachislenieController.Instance.Abit_IsOldZach('100'));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAbitZachislenieController.Suite);
end.

