unit TestCommandController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, SysUtils, Db, CommandController, Data.Win.ADODB, System.Variants;

type
  // Test methods for class TGroupController

  TestTGroupController = class(TTestCase)
  strict private
    FGroupController: TGroupController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
    procedure SetGroup;
  end;

implementation

procedure TestTGroupController.SetGroup;
begin
   FGroupController.Group := 2040;
end;

procedure TestTGroupController.SetUp;
begin
  FGroupController := TGroupController.Create;
end;

procedure TestTGroupController.TearDown;
begin
  FGroupController.Free;
  FGroupController := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTGroupController.Suite);
end.

