unit TestuLocalLogController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Windows, Forms, Dialogs, Controls, Classes,
  SysUtils, Variants, Graphics, Messages, uLocalLogController;
type
  // Test methods for class TLogController
  
  TestTLogController = class(TTestCase)
  strict private
    FLogController: TLogController;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAddEntryToFile;
  end;

implementation

procedure TestTLogController.SetUp;
begin
  FLogController := TLogController.Create;
end;

procedure TestTLogController.TearDown;
begin
  FLogController.Free;
  FLogController := nil;
end;

procedure TestTLogController.TestAddEntryToFile;
var
  str: string;
begin
  // TODO: Setup method call parameters
  FLogController.AddEntry(str);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTLogController.Suite);
end.

