unit TestuLocalLogController;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Windows, Forms, Dialogs, Controls, Classes,
  SysUtils, Variants, Graphics, Messages;
type
  // Test methods for class TLogController
  
  TestTLogController = class(TTestCase)
  strict private

  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAddEntryToFile;
  end;

implementation

procedure TestTLogController.SetUp;
begin

end;

procedure TestTLogController.TearDown;
begin

end;

procedure TestTLogController.TestAddEntryToFile;

begin
  // TODO: Setup method call parameters

  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTLogController.Suite);
end.

