program ugtuTests;
{

  Delphi DUnit Test Project
  -------------------------
  This project contains the DUnit test framework and the GUI/Console test runners.
  Add "CONSOLE_TESTRUNNER" to the conditional defines entry in the project options
  to use the console test runner.  Otherwise the GUI test runner will be used by
  default.

}

{$IFDEF CONSOLE_TESTRUNNER}
{$APPTYPE CONSOLE}
{$ENDIF}

uses
  Forms,
  TestFramework,
  GUITestRunner,
  TextTestRunner,
  TestuXMLErrorReader in 'TestuXMLErrorReader.pas',
  TestuLocalLogController in 'TestuLocalLogController.pas',
  uMain in 'Presentation\Forms\uMain.pas' {frmMain},
  uLogin in 'Presentation\Dialogs\uLogin.pas' {frmLogin},
  uDM in 'Data\uDM.pas' {dm: TDataModule},
  AbiturientOrderProcs in 'Domain\Controllers\AbiturientOrderProcs.pas',
  AbiturientBaseProcs in 'Domain\Controllers\AbiturientBaseProcs.pas',
  AbiturientBaseTables in 'Domain\Controllers\AbiturientBaseTables.pas',
  AbiturientBeforeZachislenieListProcs in 'Domain\Controllers\AbiturientBeforeZachislenieListProcs.pas',
  uBaseFrame in 'Presentation\Frames\uBaseFrame.pas' {fmBase: TFrame},
  uStudent in 'Presentation\Frames\uStudent.pas' {fmStudent: TFrame},
  uFac in 'Presentation\Frames\uFac.pas' {fmFacultet: TFrame},
  uGroup in 'Presentation\Frames\uGroup.pas' {fmGroup: TFrame},
  uSpec in 'Presentation\Frames\uSpec.pas' {fmSpec: TFrame},
  uUni in 'Presentation\Frames\uUni.pas' {fmUni: TFrame},
  uSpravFram in 'Presentation\Frames\uSpravFram.pas' {fmSprav: TFrame},
  uUchPlan in 'Presentation\Frames\uUchPlan.pas' {fmUchPlan: TFrame},
  uBaseDialog in 'Presentation\dialogs\uBaseDialog.pas' {frmBaseDialog},
  uUchPlanAddNew in 'Presentation\dialogs\uUchPlanAddNew.pas' {frmUchPlanAddNew},
  uUchPlanAddDisc in 'Presentation\dialogs\uUchPlanAddDisc.pas' {frmUchPlanAddDisc},
  uStudDlg in 'Presentation\dialogs\uStudDlg.pas' {ftmStudent},
  uPrikDlg in 'Presentation\dialogs\uPrikDlg.pas' {ftmPrikaz},
  uLangDlg in 'Presentation\dialogs\uLangDlg.pas' {ftmLangDialog},
  uRelativeDlg in 'Presentation\dialogs\uRelativeDlg.pas' {ftmAddRelative},
  uBlankRep in 'Domain\Controllers\uBlankRep.pas' {frmRepPreview},
  uGroupEdtDlg in 'Presentation\dialogs\uGroupEdtDlg.pas' {frmGroupEdt},
  uPrik in 'Presentation\Frames\uPrik.pas' {fmPrik: TFrame},
  uAbout in 'Presentation\Forms\uAbout.pas' {frmAbout},
  uNapr in 'Presentation\dialogs\uNapr.pas' {ftmNapr},
  uRaports in 'Presentation\dialogs\uRaports.pas' {frmRaporsDlg},
  uSpravForm in 'Presentation\Forms\uSpravForm.pas' {frmSprav},
  uNaprClose in 'Presentation\dialogs\uNaprClose.pas' {ftmNaprclose},
  uVosstStud in 'Presentation\dialogs\uVosstStud.pas' {frmStudVosst},
  uOtchislStud in 'Presentation\dialogs\uOtchislStud.pas' {frmOtchislStud},
  uPerevStud in 'Presentation\dialogs\uPerevStud.pas' {frmPerevStud},
  uRestoreConn in 'Domain\Controllers\uRestoreConn.pas',
  uError in 'Presentation\Forms\uError.pas' {frmError},
  uNagruzkaAddPotok in 'Presentation\dialogs\uNagruzkaAddPotok.pas' {frmAddPotok},
  uNagruzka in 'Presentation\Frames\uNagruzka.pas' {fmNagruzkaMain: TFrame},
  uNagruzkaFac in 'Presentation\Frames\uNagruzkaFac.pas' {fmNagruzkaFac: TFrame},
  uNagruzkaDep in 'Presentation\Frames\uNagruzkaDep.pas' {fmNagruzkaDep: TFrame},
  uNagruzkaAddPrep in 'Presentation\dialogs\uNagruzkaAddPrep.pas' {frmNagruzkaAddPrep},
  uStudInfo in 'Presentation\dialogs\uStudInfo.pas' {frmStudInfo},
  uNagruzkaAddKaf in 'Presentation\dialogs\uNagruzkaAddKaf.pas' {frmNagruzkaAddKaf},
  uNagruzkaAddPlan in 'Presentation\dialogs\uNagruzkaAddPlan.pas' {frmNagruzkaAddPlan},
  uNagruzkaAddDiscToPlan in 'Presentation\dialogs\uNagruzkaAddDiscToPlan.pas' {frmNagruzkaAddDiscToPlan},
  uNagruzkaAddFact in 'Presentation\dialogs\uNagruzkaAddFact.pas' {frmNagruzkaAddFact},
  uAcadem in 'Presentation\dialogs\uAcadem.pas' {frmAcademStud},
  uChangeLastName in 'Presentation\dialogs\uChangeLastName.pas' {frmChangeLastName},
  uSpecAddSpclz in 'Presentation\dialogs\uSpecAddSpclz.pas' {frmSpecAddSpclz},
  uChangePassport in 'Presentation\dialogs\uChangePassport.pas' {frmChangePassport},
  uVinEkz in 'Presentation\dialogs\uVinEkz.pas' {frmVinEkz},
  uUserFrame in 'Presentation\Frames\uUserFrame.pas' {fmUsers: TFrame},
  uAcademReturn in 'Presentation\dialogs\uAcademReturn.pas' {frmAcademReturn},
  AbiturientFacade in 'Domain\Controllers\AbiturientFacade.PAS',
  ABIT_add_nabor_dialog in 'Presentation\dialogs\ABIT_add_nabor_dialog.pas' {frmNewNabor},
  ABIT_add_rasp_dialog in 'Presentation\dialogs\ABIT_add_rasp_dialog.pas' {frmDialRasp},
  ABIT_rasp_frame in 'Presentation\Frames\ABIT_rasp_frame.pas' {fmAbitRasp: TFrame},
  ABIT_zachislenie_frame in 'Presentation\Frames\ABIT_zachislenie_frame.pas' {fmZach: TFrame},
  uDipl in 'Presentation\dialogs\uDipl.pas' {frmDiplom},
  ABIT_select_stat_year in 'Presentation\dialogs\ABIT_select_stat_year.pas' {frmBaseDialog2},
  uLevelUp in 'Presentation\dialogs\uLevelUp.pas' {frmLevelUp},
  uabitDialog in 'Presentation\dialogs\uabitDialog.pas' {frmAbitCardDialog},
  uAbitCard in 'Presentation\Frames\uAbitCard.pas' {fmAbitCard: TFrame},
  uPostupdlg in 'Presentation\dialogs\uPostupdlg.pas' {frmPostupDlg},
  ABIT_year_frame in 'Presentation\Frames\ABIT_year_frame.pas' {fmAbitYears: TFrame},
  ABIT_select_stat_ALL in 'Presentation\dialogs\ABIT_select_stat_ALL.pas' {frmBaseDialog1},
  ABIT_panel in 'Presentation\Forms\ABIT_panel.pas' {FrmPanel},
  uAbitDinamica in 'Presentation\Frames\uAbitDinamica.pas' {fmABITDinamica: TFrame},
  uAddExam in 'Presentation\dialogs\uAddExam.pas' {frmAddExamDialog},
  uPrintNapr in 'Presentation\dialogs\uPrintNapr.pas' {frmPrintNaprDialog},
  Abit_nabor_frame in 'Presentation\Frames\Abit_nabor_frame.pas' {fmAbitNabor: TFrame},
  ABIT_zhurnal in 'Presentation\Dialogs\ABIT_zhurnal.pas' {frmAbitZhurnal: TfrmAbitZhurnal},
  uUniteGroups in 'Presentation\dialogs\uUniteGroups.pas' {frmGroupManager},
  StoHTMLHelp in 'Domain\Controllers\StoHTMLHelp.pas',
  uAbitMove in 'Presentation\dialogs\uAbitMove.pas' {frmAbitMove},
  uJoinGroup in 'Presentation\dialogs\uJoinGroup.pas' {frmJoinGroup},
  uQMController in 'Domain\Controllers\uQMController.pas',
  uQueryMaster in 'Presentation\dialogs\uQueryMaster.pas',
  VarFileUtils in 'Utils\ShareAPG\VarFileUtils.pas',
  NagruzkaController in 'Domain\Controllers\NagruzkaController.pas',
  FactNagruzkaController in 'Domain\Controllers\FactNagruzkaController.pas',
  GeneralController in 'Domain\Controllers\GeneralController.pas',
  PlanNagruzkaController in 'Domain\Controllers\PlanNagruzkaController.pas',
  UchPlanController in 'Domain\Controllers\UchPlanController.pas',
  AbiturientNaborProcs in 'Domain\Controllers\AbiturientNaborProcs.pas',
  AbiturientAbitProcs in 'Domain\Controllers\AbiturientAbitProcs.PAS',
  AbiturientRaspisanieProcs in 'Domain\Controllers\AbiturientRaspisanieProcs.pas',
  ABIT_add_raspkab_dialog in 'Presentation\Dialogs\ABIT_add_raspkab_dialog.pas' {frmRaspkab: TfrmRaspkab},
  AbiturientExamProcs in 'Domain\Controllers\AbiturientExamProcs.pas',
  AbiturientListsBeforeExamProcs in 'Domain\Controllers\AbiturientListsBeforeExamProcs.pas',
  AbiturientAbitTables in 'Domain\Controllers\AbiturientAbitTables.pas',
  AppConst in 'Utils\ShareAPG\AppConst.pas',
  ClUtils in 'Utils\ShareAPG\ClUtils.pas',
  CSB in 'Utils\ShareAPG\CSB.pas',
  csdbg in 'Utils\ShareAPG\csdbg.pas',
  DbgUtils in 'Utils\ShareAPG\DbgUtils.pas',
  DBUtils in 'Utils\ShareAPG\DBUtils.pas',
  DlgUtils in 'Utils\ShareAPG\DlgUtils.pas',
  EditsEx in 'Utils\ShareAPG\EditsEx.pas',
  ExUtils in 'Utils\ShareAPG\ExUtils.pas',
  FileCls in 'Utils\ShareAPG\FileCls.pas',
  FileUtils in 'Utils\ShareAPG\FileUtils.pas',
  ggautil in 'Utils\ShareAPG\ggautil.pas',
  Iterators in 'Utils\ShareAPG\Iterators.PAS',
  MapFile in 'Utils\ShareAPG\MapFile.pas',
  OleUtils in 'Utils\ShareAPG\OleUtils.pas',
  OsUtils in 'Utils\ShareAPG\OsUtils.pas',
  PrnUtils in 'Utils\ShareAPG\PrnUtils.pas',
  QParser in 'Utils\ShareAPG\QParser.pas',
  RegUtils in 'Utils\ShareAPG\RegUtils.pas',
  SBS in 'Utils\ShareAPG\SBS.pas',
  secutils in 'Utils\ShareAPG\secutils.pas',
  StringUtils in 'Utils\ShareAPG\StringUtils.pas',
  VCLUtils in 'Utils\ShareAPG\VCLUtils.pas',
  win2000 in 'Utils\ShareAPG\win2000.pas',
  uUchPlanSemLength in 'Presentation\Dialogs\uUchPlanSemLength.pas',
  uUchPlanEditControlVZ in 'Presentation\Dialogs\uUchPlanEditControlVZ.pas',
  uUchPlanEditAuditorVZ in 'Presentation\Dialogs\uUchPlanEditAuditorVZ.pas',
  uNagruzkaAddNorm in 'Presentation\Dialogs\uNagruzkaAddNorm.pas',
  SheduleController in 'Domain\Controllers\SheduleController.pas',
  uNagruzkaEditPotokShemes in 'Presentation\Dialogs\uNagruzkaEditPotokShemes.pas',
  uNagruzkaDiscToTeacher in 'Presentation\Dialogs\uNagruzkaDiscToTeacher.pas',
  uDMStudentSelectionProcs in 'Data\uDMStudentSelectionProcs.pas' {dmStudentSelectionProcs: TDataModule},
  uDMCauses in 'Data\uDMCauses.pas' {dmCauses: TDataModule},
  uDMAdress in 'Data\uDMAdress.pas' {dmAdress: TDataModule},
  uDMStudentActions in 'Data\uDMStudentActions.pas' {dmStudentActions: TDataModule},
  uDMStudentData in 'Data\uDMStudentData.pas' {dmStudentData: TDataModule},
  uDMPrikaz in 'Data\uDMPrikaz.pas' {dmPrikaz: TDataModule},
  uDMFacultetStatistic in 'Data\uDMFacultetStatistic.pas' {dmFacultetStatistic: TDataModule},
  uDMUgtuStructure in 'Data\uDMUgtuStructure.pas' {dmUgtuStructure: TDataModule},
  uDMGroupActions in 'Data\uDMGroupActions.pas' {dmGroupActions: TDataModule},
  uDMRecordBook in 'Data\uDMRecordBook.pas' {dmRecordBook: TDataModule},
  uDMAbiturientAction in 'Data\uDMAbiturientAction.pas' {dmAbiturientAction: TDataModule},
  uDMAbiturientOtchety in 'Data\uDMAbiturientOtchety.pas' {dmAbiturientOtchety: TDataModule},
  uDMUspevaemost in 'Data\uDMUspevaemost.pas' {dmUspevaemost: TDataModule},
  uNagruzkaUchOtdelMaster in 'Presentation\Dialogs\uNagruzkaUchOtdelMaster.pas' {frmNagruzkaUchOtdelMaster},
  uNagruzkaKafedraMaster in 'Presentation\Dialogs\uNagruzkaKafedraMaster.pas' {frmNagruzkaKafedraMaster},
  uVisualDBObjectsForQM in 'Domain\Controllers\uVisualDBObjectsForQM.pas',
  uQMDataModule in 'Data\uQMDataModule.pas' {QMDataModule: TDataModule},
  uDMAbiturientZachisl in 'Data\uDMAbiturientZachisl.pas' {DMAbiturientZachisl: TDataModule},
  uNagruzkaFillTakeNagr in 'Presentation\Dialogs\uNagruzkaFillTakeNagr.pas' {frmNagruzkaFillTakeNagr},
  uNagruzkaConflictOnAvtoBuild in 'Presentation\Dialogs\uNagruzkaConflictOnAvtoBuild.pas' {frmNagruzkaConflictOnAvtoBuild},
  uNagruzkaFillFactNagrByCU in 'Presentation\Dialogs\uNagruzkaFillFactNagrByCU.pas' {frmNagruzkaFillFactNagrByCU},
  uNagruzkaFillFactNagrByVZ in 'Presentation\Dialogs\uNagruzkaFillFactNagrByVZ.pas' {frmNagruzkaFillFactNagrByVZ},
  uAbitZachislenieController in 'Domain\Controllers\uAbitZachislenieController.pas',
  uQMView in 'Presentation\Dialogs\uQMView.pas' {frmQMView},
  uDMAbiturientRasp in 'Data\uDMAbiturientRasp.pas' {DMAbiturientRasp: TDataModule},
  uNagruzkaDistributedDuty in 'Presentation\Dialogs\uNagruzkaDistributedDuty.pas' {frmNagruzkaDistributedDuty},
  uAbitRaspisanieController in 'Domain\Controllers\uAbitRaspisanieController.pas',
  uQMAddEntity in 'Presentation\Dialogs\uQMAddEntity.pas' {frmQMAddEntity},
  uNagruzkaPrepAllInfo in 'Presentation\Frames\uNagruzkaPrepAllInfo.pas' {fmNagruzkaPrepAllInfo: TFrame},
  uErrorInfo in 'Presentation\Dialogs\uErrorInfo.pas' {frmErrorInfo},
  uDMMethodWork in 'Data\uDMMethodWork.pas' {dmMethodWork: TDataModule},
  MethodWorkController in 'Domain\Controllers\MethodWorkController.pas',
  uMethodWork in 'Presentation\Frames\uMethodWork.pas' {fmMethodWork: TFrame},
  uMethodWorkDep in 'Presentation\Frames\uMethodWorkDep.pas' {fmMethodWorkDep: TFrame},
  uMethodWorkFac in 'Presentation\Frames\uMethodWorkFac.pas' {fmMethodWorkFac: TFrame},
  uMethodWorkPrep in 'Presentation\Frames\uMethodWorkPrep.pas' {fmMethodWorkPrep: TFrame},
  uMethodWorkAddNorm in 'Presentation\Dialogs\uMethodWorkAddNorm.pas' {frmMethodWorkAddNorm},
  uNagruzkaSelTeacherForFactEdit in 'Presentation\Dialogs\uNagruzkaSelTeacherForFactEdit.pas' {frmNagruzkaSelTeacherForFactEdit},
  uUspevGroupController in 'Domain\Controllers\uUspevGroupController.pas',
  uShedule in 'Presentation\Frames\uShedule.pas' {fmShedule: TFrame},
  uSheduleFac in 'Presentation\Frames\uSheduleFac.pas' {fmSheduleFac: TFrame},
  uSheduleDep in 'Presentation\Frames\uSheduleDep.pas' {fmSheduleDep: TFrame},
  uQMAdminTable in 'Presentation\Dialogs\uQMAdminTable.pas' {frmQMAdminTable},
  uQMAdminField in 'Presentation\Dialogs\uQMAdminField.pas' {frmQMAdminField},
  uMethodWorkAddPlan in 'Presentation\Dialogs\uMethodWorkAddPlan.pas' {frmMethodWorkAddPlan},
  uQMAdminRelation in 'Presentation\Dialogs\uQMAdminRelation.pas' {frmQMAdminRelation},
  SheduleTestController in 'Domain\Controllers\SheduleTestController.pas',
  SheduleAccountController in 'Domain\Controllers\SheduleAccountController.pas',
  SheduleClasses in 'Domain\Controllers\SheduleClasses.pas',
  SheduleConstraintController in 'Domain\Controllers\SheduleConstraintController.pas',
  uSheduleSetRoomConstraints in 'Presentation\Dialogs\uSheduleSetRoomConstraints.pas' {frmSheduleSetRoomConstraints},
  uSheduleAddAudEvent in 'Presentation\Dialogs\uSheduleAddAudEvent.pas' {frmSheduleAddAudEvent},
  uSheduleAddExamination in 'Presentation\Dialogs\uSheduleAddExamination.pas' {frmSheduleAddExamination},
  uSheduleAddRooms in 'Presentation\Dialogs\uSheduleAddRooms.pas' {frmSheduleAddRooms},
  uSheduleConflictLog in 'Presentation\Dialogs\uSheduleConflictLog.pas' {frmConflictEventLog},
  uLessonShedule in 'Presentation\Frames\uLessonShedule.pas' {fmLessonShedule: TFrame},
  uSheduleSemester in 'Presentation\Frames\uSheduleSemester.pas' {fmSheduleSemester: TFrame},
  uAbitOtchetsController in 'Domain\Controllers\uAbitOtchetsController.pas',
  uNagruzkaCalcUnitsContingent in 'Presentation\Dialogs\uNagruzkaCalcUnitsContingent.pas' {frmNagruzkaCalcUnitsContingent},
  uAbitNaborController in 'Domain\Controllers\uAbitNaborController.pas',
  uMethodWorkAddPlanDep in 'Presentation\Dialogs\uMethodWorkAddPlanDep.pas' {frmMethodWorkAddPlanDep},
  uMethodWorkPlanCurrentMW in 'Presentation\Dialogs\uMethodWorkPlanCurrentMW.pas' {frmMethodWorkPlanCurrentMW},
  uSelOrder in 'Presentation\Dialogs\uSelOrder.pas' {frmOrderPick},
  uExaminationShedule in 'Presentation\Frames\uExaminationShedule.pas' {fmExaminationShedule: TFrame},
  uDiplomOtdKadr in 'Presentation\Frames\uDiplomOtdKadr.pas' {fmDiplomOtdKadr: TFrame},
  uDiplOtdKardController in 'Domain\Controllers\uDiplOtdKardController.pas',
  uEnterprisePick in 'Presentation\Dialogs\uEnterprisePick.pas' {frmEnterprisePick},
  uDMOtdKadrDiplom in 'Data\uDMOtdKadrDiplom.pas' {dmOtdKadrDiplom: TDataModule},
  uMethodWorkAddGos in 'Presentation\Dialogs\uMethodWorkAddGos.pas' {frmMethodWorkAddGos},
  uMethodWorkAddContentItemGos in 'Presentation\Dialogs\uMethodWorkAddContentItemGos.pas' {frmMethodWorkAddContentItemGos},
  uMethodWorkAddContentDiscOnGos in 'Presentation\Dialogs\uMethodWorkAddContentDiscOnGos.pas' {frmMethodWorkAddContentDiscOnGos},
  DataProcessingSplashDialog in 'Presentation\Dialogs\DataProcessingSplashDialog.pas' {DataProcessingSplashDlg},
  uAddDocument in 'Presentation\Dialogs\uAddDocument.pas' {frmAddDocument},
  uAddSpecAbit in 'Presentation\Dialogs\uAddSpecAbit.pas' {frmAdditionalSpec},
  MW_PrepodPlanRep in 'Domain\Reports\MW_PrepodPlanRep.pas',
  Parser in 'Utils\Parser.pas',
  Conditions in 'Utils\Conditions.pas',
  CorrectDatatypeChecks in 'Utils\CorrectDatatypeChecks.pas',
  uLocalLogController in 'Domain\Controllers\uLocalLogController.pas',
  uNagruzkaAddCalcUnit in 'Presentation\Dialogs\uNagruzkaAddCalcUnit.pas' {frmNagruzkaAddCalcUnit},
  uLessonSheduleOnForm in 'Presentation\Forms\uLessonSheduleOnForm.pas' {LessonSheduleForm},
  uExaminationSheduleOnForm in 'Presentation\Forms\uExaminationSheduleOnForm.pas' {ExaminationSheduleOnForm},
  uAbitReturn in 'Presentation\Dialogs\uAbitReturn.pas' {frmAbitReturn},
  D_StudUspevRep in 'Domain\Reports\D_StudUspevRep.pas',
  D_GroupListRep in 'Domain\Reports\D_GroupListRep.pas',
  Barcode in 'Domain\Reports\Barcode.pas',
  ReportsBpl in 'Domain\Reports\ReportsBpl.pas',
  ReportUI in 'Domain\Reports\ReportUI.pas',
  RptColEd in 'Domain\Reports\RptColEd.pas',
  XIntf in 'Domain\Reports\XIntf.pas',
  ReportsBase in 'Domain\Reports\ReportsBase.pas',
  uWaitingForm in 'Presentation\Forms\uWaitingForm.pas' {frmWaiting},
  RegularEx in 'Domain\Common\RegularEx.pas',
  uNaprRegisterDialog in 'Presentation\Dialogs\uNaprRegisterDialog.pas' {frmNaprRegister},
  uNotError in 'Presentation\Forms\uNotError.pas' {frmNotError},
  NewClientVersionDetectedFrm in 'Presentation\Forms\NewClientVersionDetectedFrm.pas' {NewClientVersionDetectedForm},
  VersionController in 'Domain\Controllers\VersionController.pas',
  DetailsFrm in 'Presentation\Forms\DetailsFrm.pas' {DetailsForm},
  uNagruzkaSemester in 'Presentation\Frames\uNagruzkaSemester.pas' {fmNagruzkaSemester: TFrame},
  uNagruzkaSelectTeacher in 'Presentation\Dialogs\uNagruzkaSelectTeacher.pas' {frmNagruzkaSelectTeacher},
  uNagruzkaSetNormException in 'Presentation\Dialogs\uNagruzkaSetNormException.pas' {frmNagruzkaSetNormException},
  uSheduleManageBookmarks in 'Presentation\Dialogs\uSheduleManageBookmarks.pas' {frmSheduleManageBookmarks},
  D_FacItogiRep in 'Domain\Reports\D_FacItogiRep.pas',
  uXMLErrorReader in 'Domain\Controllers\uXMLErrorReader.pas' {/uMethodWorkAddWorkuMethodWorkAddWork in 'Presentation\Dialogs\uMethodWorkAddWork.pas' {frmMethodWorkAddWork},
  uMethodWorkAddWorkInNorm in 'Presentation\Dialogs\uMethodWorkAddWorkInNorm.pas' {frmMethodWorkAddWorkInNorm},
  uMethodWorkAddWork in 'Presentation\Dialogs\uMethodWorkAddWork.pas' {frmMethodWorkAddWork},
  ApplicationController in 'Domain\Controllers\ApplicationController.pas',
  uMailer in 'Domain\Controllers\uMailer.pas',
  uMethodWorkTreeView in 'Presentation\Frames\uMethodWorkTreeView.pas' {fmMethodWorkTreeView: TFrame},
  uAppTweaks in 'Presentation\Dialogs\uAppTweaks.pas' {frmAppTweaks},
  CommonNagruzkaController in 'Domain\Controllers\CommonNagruzkaController.pas',
  NagruzkaClasses in 'Domain\Controllers\NagruzkaClasses.pas',
  PreparationNagruzkaController in 'Domain\Controllers\PreparationNagruzkaController.pas',
  SheduleMainController in 'Domain\Controllers\SheduleMainController.pas',
  uNagruzkaSetVidZanyatTaskCount in 'Presentation\Dialogs\uNagruzkaSetVidZanyatTaskCount.pas' {frmNagruzkaSetVidZanyatTaskCount},
  uNagruzkaShowCalculationScheme in 'Presentation\Dialogs\uNagruzkaShowCalculationScheme.pas' {frmNagruzkaShowCalculationScheme},
  uSheduleAddAudEventWithPrefetch in 'Presentation\Dialogs\uSheduleAddAudEventWithPrefetch.pas' {frmSheduleAddAudEventWithPrefetch},
  uSheduleAddExaminationWithPrefetch in 'Presentation\Dialogs\uSheduleAddExaminationWithPrefetch.pas' {frmSheduleAddExaminationWithPrefetch},
  uDMDiplom in 'Data\uDMDiplom.pas' {dmDiplom: TDataModule},
  uDiplomController in 'Domain\Controllers\uDiplomController.pas',
  D_DiplomVipRep in 'Domain\Reports\D_DiplomVipRep.pas',
  uFindAbit in 'Presentation\Dialogs\uFindAbit.pas' {frmFindAbit},
  uAbitConfirm in 'Presentation\Dialogs\uAbitConfirm.pas' {frmAbitConfirm},
  uWaitingController in 'Domain\Controllers\uWaitingController.pas';

{$R *.RES}
{$R XML_Res.RES}

begin
  Application.Initialize;
  if IsConsole then
    TextTestRunner.RunRegisteredTests
  else
    GUITestRunner.RunRegisteredTests;
end.

